# bind9 service
# version 0.1
# Nexttop 2023-2025 (nexttop.se)
# Maintenance nexttop -> hossein a.t. (osxx.com)
#
# This composer need a ,env file be composed
#
# Default env : .env
# To compose:
#   docker compose up -d
#   docker compose down --rmi local -v
services:
  bind9:
    build:
      dockerfile: "Dockerfile"
      args:
        ADDRESS: ${BIND9_IP}
        NETWORK_SUBNET: ${NETWORK_SUBNET}
        NETWORK_MASK: ${NETWORK_MASK}
        NETWORK_GETWAY: ${NETWORK_GETWAY}
        NSLCD_IP: ${NSLCD_IP}
        NSCD_IP: ${NSCD_IP}
        CLI_IP: ${CLI_IP}
        WHMAN_IP: ${WHMAN_IP}
        LAM_IP: ${LAM_IP}
        LDAP_IP: ${LDAP_IP}
        NODEJS_IP: ${NODEJS_IP}
        PYTHON3_IP: ${PYTHON3_IP}
        OPENJDK_IP: ${OPENJDK_IP}
        BIND9_IP: ${BIND9_IP}
        OCSERV_IP: ${OCSERV_IP}
        COTURN_IP: ${COTURN_IP}
        MYSQL_IP: ${MYSQL_IP}
        MONGODB_IP: ${MONGODB_IP}
        REDIS_IP: ${REDIS_IP}
        DYNAMODB_IP: ${DYNAMODB_IP}
        ORIENTDB_IP: ${ORIENTDB_IP}
        NGINX_IP: ${NGINX_IP}
        PHPFPM_IP: ${PHPFPM_IP}
    image: bind9_image
    restart: always
    container_name: bind9
    privileged: true
    networks:
      composenetwork:
        ipv4_address: ${BIND9_IP}
    volumes:
      - ${DOCKER_DATA_PATH}/bind:/etc/bind
      - ${DOCKER_DATA_PATH}/bind/log:/var/log
    environment:
      - TESTENV=8.8.8.8
networks:
  composenetwork:
    name: cnetwork
    driver: bridge
    ipam:
     config:
       - subnet: ${NETWORK_SUBNET}
         gateway: ${NETWORK_GETWAY}
